// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXhZV9kCwngHxgBEOmDYY_BmzQhNlFdYE',
    appId: '1:575385173021:web:581537476346983400daf4',
    messagingSenderId: '575385173021',
    projectId: 'shokh-e14d6',
    authDomain: 'shokh-e14d6.firebaseapp.com',
    storageBucket: 'shokh-e14d6.appspot.com',
    measurementId: 'G-4J59F5E1HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbQf9ibd50uS2tKZV3b02g2V1w4Chl5xE',
    appId: '1:575385173021:android:422ad2076a964c1900daf4',
    messagingSenderId: '575385173021',
    projectId: 'shokh-e14d6',
    storageBucket: 'shokh-e14d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbvyPLT4ywJiFfx2NPta3Gc-LVSjS6ac',
    appId: '1:575385173021:ios:6712596f622e382900daf4',
    messagingSenderId: '575385173021',
    projectId: 'shokh-e14d6',
    storageBucket: 'shokh-e14d6.appspot.com',
    iosClientId: '575385173021-2a0dpbfidlprkok6a33fva3k652usue8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokh',
  );
}
